### ISSUE TITLE
Event documentation: eventType or entityType.

### ISSUE THREAD

**Issue by rverberne** [opentripmodel/otm5-change-requests#10]
**Type of bug**
- [X] Inconsistency or contradiction in the specification
- [ ] Fault in the representation (rendering) of the specification
- [ ] Other (please describe below)

**Describe the bug**
In the documentation for `PUT /events` I see a required attribute named `entityType` directly in the Event itself. Has this been renamed from `eventType` to `entityType` or has it always been `entityType`? The `eventType` attribute is still visible and required for `associationCreatedEvent` and `associationRemovedEvent`.
Is the current documentation correct?

**Comment by bmeesters** [comment]
Thanks @rverberne for your contribution again. I don't think it changed in the last few months, but if it did it was not on purpose. Originally the discriminator for entities is named entityType, for actions it's actionType, and for events it's eventType. But since actions and events are also entities, we could make it simpler and just use entityType everywhere. What do you think?

**Comment by rverberne** [comment]
I recommend specific discriminators per entity. Then you can do this:

```
{
  "eventType": "updateEvent",
  "entity": {
    "entityType": "action",
    "actionType": "load",
    "name": "Load name"
  }
}
```
If you name it `entityType` everywhere then there would be a collision between `entityType` and `actionType`. I see you can not use `action` in `updateEvent` but let's say you would want to do that, of with another type.

I would reserver the attribute `entityType` for places where the entity type can be anything, like in the `updateEvent`.

**Comment by bmeesters** [comment]
Unfortunately OpenAPI does not completely play nice with that, or at least it will not be rendered properly (already tried that before). I don't think `"entityType": "action"` is currently used anywhere. The current specification treats `load` as both the actionTypr and the entityType. I don't know for sure if we can change that (easily).

**Comment by bmeesters** [comment]
I will at least check whether I can change it to eventType, because that would be more consistent.

**Comment by rverberne** [comment]
So, just to confirm: In the Event object, the discriminator attribute is `eventType`? The documentation still shows `entityType` with the dropdown list.

**Comment by bmeesters** [comment]
Yes it is, so it is indeed a bug in the specification.

**Comment by bmeesters** [comment]
@rverberne it has been fixed (https://otm5.opentripmodel.org/#tag/Event/paths/~1api~1v5~1events/put)
