### ISSUE TITLE
Add Transport Mode 

### ISSUE THREAD

**Issue by woutvandenheuvel** [opentripmodel/otm5-change-requests#12]
**Type of request**
- [x ] I'd like to add something to the OTM 5 spec
- [ ] I'd like to change something in the OTM 5 spec

**Is your feature request related to a problem?**
If so, please describe the problem. For example: with the current specification I cannot model [...]. Or: I'm unable to
provide the use case [...].
Add the mode of transport. Description The mode and means of transport as used for the movement of goods
suggested values: 
reference https://unece.org/fileadmin/DAM/cefact/recommendations/rec19/rec19_01cf19e.pdf

**Describe the solution you'd like**
What would you like to add or change to the specification? Please be as clear and concise as possible.
0 Transport mode not specified
Transport mode has not been specified
Notes:
1) This code can be used when the mode is not known or when information on it is not
available at the time of issuing the document concerned.
| 1 Maritime transport
Transport of goods and/or persons is by sea.
| 2 Rail transport
Transport of goods and/or persons is by rail.
| 3 Road transport
Transport of goods and/or persons is by road.
| 4 Air transport
Transport of goods and/or persons is by air.
| 5 Mail
Method to convey goods is by mail
Notes:
1) This code is provided for practical reasons, despite the fact that mail is not a genuine mode
of transport. In many countries, the value of merchandise exported and imported by mail is
considerable, but the exporter or importer concerned would be unable to state by which
mode postal items had been conveyed.
| 6 Multimodal transport
Method to convey goods and/or persons is by multimodal transport.
Notes:
1) This code is provided for practical reasons, despite the fact that multimodal transport is not
a genuine mode of transport. It can be used when goods are carried by at least two
different modes from a place at which the goods are taken in charge by a transport operator
to a place designated for delivery, on the basis of one transport contract. (Operations of
pick-up and delivery of goods carried out in the performance of a single mode of transport,
as defined in such a contract, shall not be considered as multimodal transport).
| 7 Fixed transport installation
Transport of item is via a fixed transport installation.
Notes:
1) This code applies to installations for continuous transport such as pipelines, ropeways
and electric power lines.
| 8 Inland water transport
Transport of goods and/or persons is by inland water.
#| 9 Transport mode not applicable
The mode of transport is not applicable

**Describe alternatives you've considered**
Did you try to solve it with the current specification? If so, how? Please be as clear and concise as possible.

**Additional context**

**Comment by bmeesters** [comment]
I think adding transport mode is a valuable addition. However I think we should add the modality to the trip and not to goods. Using actions you can see which goods are part of which trips. This gives you the ability to precisely model how some goods came from one location to its final destination in a way the current proposal cannot. Using this method you don't really need a multi-modal case anymore as well. It also allows us to be more precise in trips themselves.

Is that a valid alternative @woutvandenheuvel?

**Comment by thomaskolmans** [comment]
Is this not partially covered by the `vehicleType` constraint? Aside from that, I would like to have it added not just to the `Trip` in case it does get added but also the `MoveAction` as these do not have to relate necessarily - if added of course.

**Comment by bmeesters** [comment]
vehicle constraints were originally meant to be a bit more specific. I.e. you do not only need a truck, but a truck with some cooling options. Though looking at the specification I think this constraints needs some more attention since you cannot truly express that.

Also, IMO, a simple field on the trip (and move action) is a lot simpler to process than a constraint. Constraints in general have some ergonomic problems, but for some use cases (such as time windows, etc.) I think they make sense, since the alternatives are also somewhat complex or not generic enough.

I am still in favor of just adding the field. @thomaskolmans do you agree?

**Comment by thomaskolmans** [comment]
Yes - I agree, with then the note to _also_ add it to the `MoveAction` and the `Trip` model.

**Comment by bmeesters** [comment]
Closing this as it is now official part of OTM5.1
