### ISSUE TITLE
Add emission standard

### ISSUE THREAD

**Issue by woutvandenheuvel** [opentripmodel/otm5-change-requests#13]
**Type of request**
- [x ] I'd like to add something to the OTM 5 spec
- [ ] I'd like to change something in the OTM 5 spec

**Is your feature request related to a problem?**
If so, please describe the problem. For example: with the current specification I cannot model [...]. Or: I'm unable to
provide the use case [...].
Emission standard of the vehicle is missing in OTM

**Describe the solution you'd like**
What would you like to add or change to the specification? Please be as clear and concise as possible.
Add to vehicle. Emission standard of the vehicle / mode of transport
Suggested values
Euro 0
Euro 1
Euro 2
Euro 3
Euro 4
Euro 5
Euro 6

**Describe alternatives you've considered**
Did you try to solve it with the current specification? If so, how? Please be as clear and concise as possible.

**Additional context**

**Comment by bmeesters** [comment]
Seems like a logical addition, and technically easy enough to add. Though from a more technical perspective, we need to think whether we want to use separate fields for different types of vehicles better. Now you can set car/truck oriented fields while you describe a barge.

**Comment by bmeesters** [comment]
Closing this as it is now official part of OTM5.1
