### ISSUE TITLE
Documentation: Association -> Reference -> EntityType Enum is still V4 spec

### ISSUE THREAD

**Issue by thomaskolmans** [opentripmodel/otm5-change-requests#14]
**Type of bug**
- [x] Inconsistency or contradiction in the specification

**Describe the bug**
The title pretty sums it up pretty well. Enum is still the old specification.

"actor" "constraint" "location" "route" "sensor" "shipment" "trip" "vehicle" "consignment" "transportOrder" "goods" "action" "loadShipment" "unloadShipment" "receiveShipment" "releaseShipment" "stop" "move" "genericAction" "load" "unload" "associationCreated" "associationRemoved" "updateEvent" "locationUpdate" "sensorUpdate" "startWaiting" "stopWaiting" "startMoving" "stopMoving" "startEngine" "stopEngine"

In V5 there should not be any reference to "shipment" for instance.

**Comment by bmeesters** [comment]
Again, nice catch. I'll be doing an update and taking this along. Should be fixed before the end of the week. Thanks again for your contribution.

**Comment by bmeesters** [comment]
I fixed it @thomaskolmans, the documentation is updated again so I am clossing this issue.
