### ISSUE TITLE
Add wait/break actions

### ISSUE THREAD

**Issue by bmeesters** [opentripmodel/otm5-change-requests#17]
**Type of request**
- [x] I'd like to add something to the OTM 5 spec
- [ ] I'd like to change something in the OTM 5 spec

**Is your feature request related to a problem?**
_If so, please describe the problem. For example: with the current specification I cannot model [...]. Or: I'm unable to
provide the use case [...]._

Currently we can model certain actions during a trip on the `stops` and the `moves`. However we cannot properly model that a driver has a planned break, or that the driver has to wait (because the dock is still occupied).

**Describe the solution you'd like**
_What would you like to add or change to the specification? Please be as clear and concise as possible._

I would like to add two new actions: `wait` and `break`. The difference is that a break is a planned break that every driver has right to. No matter whether there are traffic jams, or unexpected trouble during the trip, a driver always is allowed to take the break time. The wait time is different, since sometimes you have to wait since there was no optimal planning in which you can directly enter a dock. However if you are late, you do not have to wait the `wait` time since you already had that wait time on the road.

**Describe alternatives you've considered**
_Did you try to solve it with the current specification? If so, how? Please be as clear and concise as possible._

Currently we are modeling it with genericActions, but those are not ideal, especially not since it is hard to differentiate `break` and `wait` times.

**Additional context**

**Comment by thomaskolmans** [comment]
Can you give an example of how these actions look? Any new properties?

**Comment by bmeesters** [comment]
I would say they share the same properties that most other actions share:
* The shared entity data (UUID, name, external attributes, creation date, last modified date)
* lifecycle
* start and end time
* remark
* actions
* constraint
* A reason (only on the wait)

You could also argue to add a location I suppose. Though as far as I am aware systems do not enforce where to take a break. And from a privacy point of view I am not sure systems are even allowed to say whether a driver took a break at some McDonalds.

Some silly example:

```json
{
    "id": "82aaffea-45e1-4c19-8720-ef44bc9a1968",
    "name": "Lunch break",
    "remark": "Everybody deserves a break once in a while",
    "startTime": "2021-07-13T11:00:00Z",
    "endTime": "2021-07-13T11:30:00Z",
    "actionType": "break"
}
```

and 

```json
{
    "id": "cfb71ae8-ef85-4529-9b65-b2a3c8bc5aaa",
    "name": "Waiting..",
    "remark": "We hope this is not going to take too long",
    "reason": "Dock is occupied",
    "startTime": "2021-04-13T10:00:00Z",
    "endTime": "2021-04-13T11:00:00Z",
    "actionType": "wait"
}
```

Any thoughts or suggestions on this @thomaskolmans?

**Comment by thomaskolmans** [comment]
I'd like to add a `location`  and `trip`.

**Comment by bmeesters** [comment]
I suppose those make sense, since they are both also part of the `stop`. And these actions are comparable.

**Comment by woutvandenheuvel** [comment]
In Europe strict regulations apply for activities as working times,  driving time and rest periods in the road transport sector. In OTM we should refer to the applicable regulations in order to prevent misinterpretation between among others; employers and employees and between companies/drivers and enforcement authorities 
Attached document contains the main categories including a description and a link to the source documentation. 
[definitions working time-break-rest.pdf](https://github.com/opentripmodel/otm5-change-requests/files/6952931/definitions.working.time-break-rest.pdf)

**Comment by bmeesters** [comment]
Thanks @woutvandenheuvel, I can make a proposal and post it here based on the document.

**Comment by woutvandenheuvel** [comment]
@bmeesters Document updated with few improvements
[definitions working time-break-restv0.1.pdf](https://github.com/opentripmodel/otm5-change-requests/files/6960502/definitions.working.time-break-restv0.1.pdf)

**Comment by bmeesters** [comment]
This is now part of OTM5.2
