### ISSUE TITLE
Support more location types

### ISSUE THREAD

**Issue by bmeesters** [opentripmodel/otm5-change-requests#22]
**Type of request**
- [x] I'd like to add something to the OTM 5 spec
- [ ] I'd like to change something in the OTM 5 spec

**Is your feature request related to a problem?**
If so, please describe the problem. For example: with the current specification I cannot model [...]. Or: I'm unable to
provide the use case [...].

Planning systems often refer to a location as an 'operational base' for locations that house all vehicles (at least administratively) This helps grouping trips and provides more information for systems, even if the location is not actually visited. Currently OTM does not support the `operationalBase` as a location type.

**Describe the solution you'd like**
What would you like to add or change to the specification? Please be as clear and concise as possible.

At it is a type on location.

**Describe alternatives you've considered**
Did you try to solve it with the current specification? If so, how? Please be as clear and concise as possible.

None

**Additional context**

**Comment by bmeesters** [comment]
@woutvandenheuvel we talked about this before. I think it would be a good addition, and we actually need something like this to properly group planning data from incoming systems. Do you also still agree this is a good idea?

**Comment by woutvandenheuvel** [comment]
@bmeesters Agree that this is a good idea. Please check with Menno Lambooy as well. Operational base is comparable for the by CBS requested filed 'Standplaats'

**Comment by bmeesters** [comment]
I will check with Menno as well, 'Standplaats' can indeed be replaced with 'operational base'

**Comment by thomaskolmans** [comment]
This sounds like a good addition! Thanks.

**Comment by bmeesters** [comment]
Also discussed with Menno Lambooy, he is also in favor. Powerbricks and CBS also want this.

**Comment by bmeesters** [comment]
This is now part of OTM5.2
