### ISSUE TITLE
Change the HTTP reponse code voor DELETE requests to "204 No Content"

### ISSUE THREAD

**Issue by mbusger** [opentripmodel/otm5-change-requests#23]
**Type of request**
- [ ] I'd like to add something to the OTM 5 spec
- [X] I'd like to change something in the OTM 5 spec

**Is your feature request related to a problem?**
In the current situation, whenever I receive a DELETE request, I can not both delete the actual object and return it as the response of the request.

**Describe the solution you'd like**
Whenever a DELETE request is sent to a server, the server can process it and send back a "204 No Content" without an actual payload.

**Describe alternatives you've considered**
I've considered to save the payload of the request and just send that back whenever a DELETE request comes in, but seeing as this payload has no value whatsoever (as the object in question gets deleted anyway) it seems unneccesary to also return the object as payload when you receive a DELETE request.

**Additional context**
N/A

**Comment by bmeesters** [comment]
Hello @mbusger, thanks for your contribution. I agree that providing the content of something that you deleted is not very valuable. However, changing this would be backwards incompatible, so we might want to introduce a 'new way' to delete and deprecate the old way of deleting so we do not have to bump our version to OTM6.

I'll get back to you on this.

**Comment by bmeesters** [comment]
Now that I think a bit more about it I don't think this is backwards incompatible as long as we still support the previous version. So with that I think this is a good improvement. I think this can be part of OTM5.3

**Comment by bmeesters** [comment]
Note though that OTM5.2 released today and this was just a little too late to be considered. So it will be part of OTM5.3 in three months. You can of course already go ahead and implement it on your side if it is otherwise blocking.

**Comment by mbusger** [comment]
Thanks, that's great to know. I will already start with implementing it on our side then.

**Comment by bmeesters** [comment]
This has been implemented in OTM5.3 released today and thus can be closed
