### ISSUE TITLE
Add Consignment association to the generic action

### ISSUE THREAD

**Issue by gerardpeters** [opentripmodel/otm5-change-requests#24]
**Type of request**
- [X] I'd like to add something to the OTM 5 spec
- [ ] I'd like to change something in the OTM 5 spec

**Is your feature request related to a problem?**
I'm trying to model some actions that takes place in our system that I cannot map to the existing actions. I wanted to use the generic action but this one lacks a consignment association.

**Describe the solution you'd like**
A generic action can take place on more entities than a Trip I guess. In our case the action takes place on a consignment. It would be helpfull that, next to the trip, an optional Consignment assocation could be included in the generic action.

**Comment by bmeesters** [comment]
I get the requirement, and think it could be useful. Though again - like in https://github.com/opentripmodel/otm5-change-requests/issues/25 - I am more interested in what type of action you are missing. The GenericAction is more of a fallback, if all else fails. I rather look at how we do not need it then on how to extend it.
