### ISSUE TITLE
Ability to add the actors involved in a generic action

### ISSUE THREAD

**Issue by gerardpeters** [opentripmodel/otm5-change-requests#25]
**Type of request**
- [X] I'd like to add something to the OTM 5 spec
- [ ] I'd like to change something in the OTM 5 spec

**Is your feature request related to a problem?**
When performing a generic action, one or more actors are involved. In our situation a generic action is done by a carrier but there is no way of adding the actor(s) in a generic action.

**Describe the solution you'd like**
An property Actors to add one or more actorassociations that are involved in the action.

**Comment by bmeesters** [comment]
Hello @gerardpeters, thanks for your contribution. 

Currently there are no actors on any action. So I would be either in favor of adding it to all actions or none. That said, I have not seen a use case for an actor on an action yet. So, I am actually more interested in what type of action you are missing and why you need actors on that. It might be something universal to could be added as a new action.

**Comment by gerardpeters** [comment]
Hi @bmeesters ,

What I'm trying to achieve is the following:
1. A consignment is send to a Carrier;
2. The carrier can either accept or reject the transport of this consigment

Those Accept en Reject actions are the ones that I'm trying to model. I had another look at OTM but maybe an AssociationCreatedEvent and an AssociationRemovedEvent event are better ways to model this? Any thoughts?

**Comment by bmeesters** [comment]
It depends a little bit on what the carrier wants to send back. Does it include a planning? E.g. the planned start and end times of the pickup/delivery? Or only the actor that is supposed to deliver the consignment?

If the carrier only supplies the actors then indeed you can just create an AssociationCreatedEvent with the actor and the consignment to model the same thing. You can use the AssociationRemovedEvent to indicate that they rejected it. 

If the consignment contains more information than just the actor, for example the actors **and** the load/unload actions **and** the new status (planned) you can also use an UpdateEvent and send the same consignment with the added information in its actors/actions. You can use this same event with the consignment and the status cancelled to indicate that they rejected it.

Does any of this work for you?

**Comment by gerardpeters** [comment]
Hi Bas,

That would do the trick I think. I'll use UpdateEvent in combination with the assiocationcreated/removed events. 

Thanks!

**Comment by bmeesters** [comment]
Happy to help! Feel free to keep asking questions / suggestions with problems you encounter.
