### ISSUE TITLE
Add node to Goods for Goods code classification structure

### ISSUE THREAD

**Issue by BobZuidhoek** [opentripmodel/otm5-change-requests#26]
**Type of request**
- [ ] I'd like to add something to the OTM 5 spec

**Describe the solution you'd like**
Many roadfreight carriers provide Customs brokerage services on behalf of shippers. These Customs brokerage services are performed for export or transit to non-EU countries (e.g. UK, Switserland, Norway, etc.). To be able to do that, roadfreight need to be instructed with a Goods classification codes breakdown of goods-lines. 

It's important to consider that a goods line can have a **breakdown** specification into several (1:n) goods classification lines of a certain goods classification type. From a Customs point of view, many products that are shipped do not just have 1 goods classification, but many (because they keep to be seen as composite products). 

For example we have 1 Goods object, being gross weight 500 kgs net weight 450 kgs of "Mixed bouquet flowers" with a line value of 500 EUR. This can be broken down into a Goods Classiciation section:
  --> Classiciation type: HS-code
        --> Classificiation line 1: Classification code 06031100, Description "Roses', Reporting quantity 5000, Reporting type Stem, Gross weight 250 kgs, Net weight 275 kgs, Value 425.0000, currency EUR. 
         --> Classificiation line 2: Classification code 06031200, Description "Tulips', Reporting quantity 2500, Reporting type Stem, Gross weight 250 kgs, Net weight 275 kgs. Value 600.0000, currency EUR. 
  --> Classiciation type: Botanical_class
        --> Classificiation line 1: Classification code Rosa sp., Description "Roses sp.', Reporting quantity 5000, Reporting type Stem, Gross weight 250 kgs, Net weight 275 kgs.
         --> Classificiation line 2: Classification code Tulipa sp., Description "Tulipa sp.', Reporting quantity 2500, Reporting type Stem, Gross weight 250 kgs, Net weight 275 kgs.

There are also other Classification types, such as TARIC (the EU's further composition of HS-codes). 

Of course the actual domain model for this needs to be studied deeper. Standards such as UBL also provide for a section to make this breakdown. 

The Classification types should be an enumeration list, maintained by OTM5. 

**Describe alternatives you've considered**
External attributes, but these do not seem a great place for this layered structure. 

**Additional context**
None

**Comment by bmeesters** [comment]
Hello @BobZuidhoek, thanks for your contribution. Since I am not an expert on this topic I need a little more details. Could you create an example in how you would wish OTM looked like (in JSON if possible)? If I understand you correctly you would want one extra field on `Goods`, the _classification_ that can contain multiple lines?

**Comment by BobZuidhoek** [comment]
![IFTMIN text](https://user-images.githubusercontent.com/90270072/132642090-09ccfb06-efb0-447e-bda7-ee916c70d3f5.png)
![ERD](https://user-images.githubusercontent.com/90270072/132643209-2eb4858a-3c4c-4f58-884c-f365a59e61cf.jpg)

Hi Bas, 

Find attached an ERD and some notes in it with my take on what this datamodel could look like. Hope that helps. 

I've also included a text from the (old) IFTMIN Edifact documentation, where you see that an item can be described in 1 or more tariff codes. I've worked with many logistics systems throughout may career, and in some of them the oversimplified assumption is made that a Goods only has 1 classification (for example they put an attribute such as HS-code in the Goods node itself). For many industries, that simplified setup does not work (because they ship composites that for example for Customs reasons keep to be viewed as separate parts). I still see the oversimplification get implemented in many systems, and once it's in there, it's very hard to refactor if after. That's why I've started this issue, to help prevent you from going down the wrong route.  

Do note that I'm still slightly confused with how Goods should work in TransportOrders in OTM. In the UBL TransportExecutionPlanRequest message, there was a distinction between Handling Unit and GoodsItem. With that setup, you could correctly layer things. Granted, documentation around this on how to implement certain scenario's was always lacking, resulting in mostly messy and mis-interpreted implementations. But technically, the idea behind it was OK. 

I hope the DALTI community can chime in on how this goods-describing logic is implemented in their TMS systems, ERD-model wise speaking. But be aware to also stumble upon the oversimplified situations in there as well.

**Comment by bmeesters** [comment]
Thanks! This definitely clarifies a lot. Note that in OTM Goods can be nested. You either have the singular level 'items' or a 'transportEquipment' that contains 'items' or even other 'transportEquipments', similar to Handling Unit and GoodsItemin UBL.

So, for example, if you want to model a pallet containing a box with 2 types of flowers you could do something like this in pseudo OTM:

```
goods
  type: transportEquipment
  equipmentType: pallet
  subEquipmentType: EUR6
  containedGoods: 
    goods
      type: transportEquipment
     equipmentType: box
     containedItems:
       goods
          type: items
          productType: flowers type 1
          quantity: 3
          ... etc.
       goods
          type: items
          productType: flowers type 2
          quantity: 2
          ... etc.

```

Given the above example and your notes. I think that the a single goodsItem should have only one classification code. Since you can nest the different flowers below a transportEquipment. Does this make sense to you and do you agree? Or do you feel that despite the nesting we need multiple classification codes per goods item?

**Comment by BobZuidhoek** [comment]
Hi Bas,

The layering clarifies a lot about how the physical product is layered. However, I do think the GoodClassification requirement remains. 

The way I look at this, is that the Good itself is what the product is commercially/logistically called. The Goodsclassification of the Good is a breakdown in itself, but the idea here is that is **_describes_** the product for Customs purposes (without strictly saying the Good itself consists of several individual divisible parts). 

I'm making the following example up, so just follow may train of thought instead of debating whether this sunscreen-situation exists in real life. 

Let say a shipper want to transports sunscreens. However, it could be the situation that a sunscreen, for Customs purposes and HS-code classification, is seen as part 'machine' and part 'cloth'. This means that: 
 - The commercial/logistical product being transported are sunscreens. Also, if you would look at the commercial invoice, there would be an invoice line that states "Sunscreens". 
 - The Goods classification breakdown is type HS-code, and then (line 1) machine and (line 2) cloth. Each line having it's own attributes (HS-code, kg, value, etc.). On a commercial invoice, you would find this HS-code breakdown printed at the bottom of the invoice. 

The situation you find above is that the Good is the sunscreen. For GoodsClassifcation (Customs) purposes, it is described/specified as having separate ingredients having separate coding, weight, value, etc. But this is the punchline: from a product point of view, the Sunscreen shouldn't be viewed as a Good that can be taken apart (it's still the whole sunscreen). Therefore, I don't see GoodsClassification as sub-layering Goods itself. 

The same goes with Flowers that are in mixed bouquets. The products being shipped are "mixed bouquets" (and essentially should not be seen as a separable product). But only for Customs purposes, the product needs to be described differently.

**Comment by bmeesters** [comment]
I see, yes I understand your concern. So the proposed change, if I understand correctly. Is to add an optional field to Goods called `classification`. and a classification then might contain multiple lines with details. So your sunscreen example would then become:

```
goods
  type: items
  product type: sunscreen
  weight (net weight, non mandatory): 10 kg
  classification
    line
      code: <some hs code>
      description: cloth
      weight:L 1kg
   line
     code: <some other hs code>
     description: machine
     weight: 9 kg 
```

Would that  work for you? And if so, what  details does the classification line need?

**Comment by BobZuidhoek** [comment]
Indeed, you're on the right track I think. 

Building onto your example:

goods
  type: items
  product type: sunscreen
  weight (net weight, non mandatory): 10 kg
  etc. all other already available fields...
  classification (NEW FIELD)
    classification type, type: HS    
      line
        key-name: code, value: some hs code        
        key-name: description, value: consumer machines
        key-name: gross_weight, value: 7kg
        key-name: net_weight, value: 6kg
        key-name: statistical_qty, value: 7
        key-name: statistical_qty_UOM, value: KG
        key-name: customs-value: 500
        key-name: customs-value-currency: EUR
      line
        key-name: code, value: some hs code        
        key-name: description, value: textile
        key-name: gross_weight, value: 3kg
        key-name: net_weight, value: 2.25kg
        key-name: statistical_qty, value: 40
        key-name: statistical_qty_UOM, value: M2
        key-name: customs-value: 325
        key-name: customs-value-currency: EUR
    classification type, type: TARIC    
      line
        key-name: code, value: some taric code        
        key-name: description, value: household appliances
        key-name: gross_weight, value: 7kg
        key-name: net_weight, value: 6kg
        key-name: statistical_qty, value: 7
        key-name: statistical_qty_UOM, value: KG
        key-name: customs-value: 500
        key-name: customs-value-currency: EUR
      line
        key-name: code, value: some taric code        
        key-name: description, value: textile non-industrial
        key-name: gross_weight, value: 7kg
        key-name: net_weight, value: 2.25kg
        key-name: statistical_qty, value: 40
        key-name: statistical_qty_UOM, value: M2
        key-name: customs-value: 325
        key-name: customs-value-currency: EUR

Within lines, I advise to work with key/value pairs. The required fields (keys) required within a line vary wildly for different coding-systems and situations. The key's can be standardized/prescribed by OTM, but do not come from a mandatory enumeration list.

**Comment by bmeesters** [comment]
Thanks Bob, this is a valuable addition. I think we go with optional fields instead of key-value pairs instead for the most common ones. Maybe also have room for key-value pairs for others. I contacted some other people in the field to discuss some more details.

Note that OTM5.2 just released today and OTM5.3 is planned for December, so we have some time to get it right.

**Comment by BobZuidhoek** [comment]
Perfect! And indeed, a couple of sense-checks with others in the field are highly necessary with this subject.

**Comment by svendrig** [comment]
> Indeed, you're on the right track I think.
> 
> Building onto your example:
> 
> goods __type: items __product type: sunscreen __weight (net weight, non mandatory): 10 kg __etc. all other already available fields... __classification (NEW FIELD) ____classification type: HS ______line ________key-name: code, value: some hs code ________key-name: description, value: consumer machines ________key-name: gross_weight, value: 7kg ________key-name: net_weight, value: 6kg ________key-name: statistical_qty, value: 7 ________key-name: statistical_qty_UOM, value: KG ________key-name: customs-value: 500 ________key-name: customs-value-currency: EUR ______line ________key-name: code, value: some hs code ________key-name: description, value: textile ________key-name: gross_weight, value: 3kg ________key-name: net_weight, value: 2.25kg ________key-name: statistical_qty, value: 40 ________key-name: statistical_qty_UOM, value: M2 ________key-name: customs-value: 325 ________key-name: customs-value-currency: EUR ____classification type: TARIC ______line ________key-name: code, value: some taric code ________key-name: description, value: household appliances ________key-name: gross_weight, value: 7kg ________key-name: net_weight, value: 6kg ________key-name: statistical_qty, value: 7 ________key-name: statistical_qty_UOM, value: KG ________key-name: customs-value: 500 ________key-name: customs-value-currency: EUR ______line ________key-name: code, value: some taric code ________key-name: description, value: textile non-industrial ________key-name: gross_weight, value: 7kg ________key-name: net_weight, value: 2.25kg ________key-name: statistical_qty, value: 40 ________key-name: statistical_qty_UOM, value: M2 ________key-name: customs-value: 325 ________key-name: customs-value-currency: EUR
> 
> Within lines, I advise to work with key/value pairs. The fields (keys) required within a line vary wildly for different coding-systems and situations. The keys can be standardized/prescribed by OTM, but do not come from a mandatory enumeration list.

Good advise to use key/value pairs, it makes it more flexible and future proof.
Already one key comes up in mind reading this:  Country of origin

**Comment by bmeesters** [comment]
Personally I would recommend against key/value pairs. It is easy to make typos or use different capitalization and still be valid according to the specification. It also goes against the idea of maintaining our own code lists (see https://github.com/opentripmodel/otm5-change-requests/issues/27)

I rather look at what we want to include for certain and extend that over time. Maybe have some sort of fallback (e.g. add a field others that contain key/values). Any thoughts on this approach @BobZuidhoek and @svendrig ?

**Comment by BobZuidhoek** [comment]
I see the optimal scenario being a combination of prescribed keys (from a code list) with the option for an occasional escape where needed. Technically however, that would still mean you would have a key/value system in place. 

Of course you could promote common attributes to fully named fields. My experience with this subject however, is that the fields vary wildly and you rather want flexibility as to not having to adapt software all the time to cope with new named fields.

**Comment by bmeesters** [comment]
I am no expert on this matter, but I assume that goods classification codes do not change continuously? 

> Of course you could promote common attributes to fully named fields.

This was indeed my intention (each of them optional), where we can promote more key/value pairs if they are desired. If we are going to maintain code lists I think it would make sense to add them to the spec directly. OTM tries to support escape hatches where necessary. But it should be clear that it is an escape hatch and we want to stimulate users to add _change requests_ to notify us of shortcomings instead of leaning on the escape hatches forever.

So it would then look something like:
```
goods
__type: items
__product type: sunscreen
__weight (net weight, non mandatory): 10 kg
__etc. all other already available fields...
__classification (NEW FIELD)
____classification type: HS
______line
________code: some hs code
________description: onsumer machines
________gross_weight: 7kg
________weight: 6kg
________others: (NOTE, this is just an arbitrary selection of promoted items)
__________key-name: statistical_qty, value: 7
__________key-name: statistical_qty_UOM, value: KG
__________key-name: customs-value: 500
__________key-name: customs-value-currency: EUR
______line
________etc
```

**Comment by bmeesters** [comment]
Hello @BobZuidhoek, trying to create the overview issue I came to the conclusion that we never decided which fields should be supported on the `classificationLine`. I am personally not a fan of just adding key-value pairs since then we would need to check what code-list is supported anyway. Do you have a list of items that need to be promoted to the classification line? (We can still have the escape hatch, but it would be nice if we can avoid it since can result in typos, different conventions, etc.)

**Comment by bmeesters** [comment]
This has been implemented in OTM5.3 released today and thus can be closed. There is still room for more classification lines but those can still be added in a backwards compatible fashion later. These can be added as new change requests.
