### ISSUE TITLE
Add fields to ADR

### ISSUE THREAD

**Issue by etwobben** [opentripmodel/otm5-change-requests#31]
**Type of request**
- [x] I'd like to add something to the OTM 5 spec
- [ ] I'd like to change something in the OTM 5 spec

**Is your feature request related to a problem?**
We would like all the information of ADR to be present in the OTM entity. This also includes the points and transportClass field. 

**Describe the solution you'd like**
Two new fields in the ADR object;

- points; number field
- transportClass; enum (I, II, III, IV) or number field with checks that the value is 1-4.

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by bmeesters** [comment]
Thanks again for your contribution @etwobben. Since I am not that knowledgeable about ADRs I need to check this with some other people. But if this is indeed part of the official ADR definition we will just add it. I'll get back to you on Thursday.

**Comment by bmeesters** [comment]
We discussed it and indeed these are missing from the OTM5 specification, we will add them in OTM5.3

**Comment by bmeesters** [comment]
Hello @etwobben it was pointed out to me that _transport class_ is an older name and it might overlap with the already present field `class`. Though this enum has in total 13 options (divided over 9 different classes). Just to be sure, is this not the field you want?

And if not, do the transport classes also have 'readable' names to distinguish them by except for some number?

**Comment by etwobben** [comment]
@bmeesters The existing `class` is the class of the goods. Transport category is perhaps the better naming. See [this](https://specialcargo.nl/adr.php) in the first column.

**Comment by bmeesters** [comment]
Thanks for getting back to me. I'll do a final check (since I am not an expert in this area). But if it is indeed missing it can just be added.

**Comment by bmeesters** [comment]
@etwobben I got confirmation that this indeed can be added. Just wondering what would be the best name? Transport class or transport category?

**Comment by bmeesters** [comment]
This has been implemented in OTM5.3 released today and thus can be closed.
