### ISSUE TITLE
Add `relatedConsignments` to consignments

### ISSUE THREAD

**Issue by bmeesters** [opentripmodel/otm5-change-requests#32]
**Type of request**
- [x] I'd like to add something to the OTM 5 spec
- [ ] I'd like to change something in the OTM 5 spec

**Is your feature request related to a problem?**
If so, please describe the problem. For example: with the current specification I cannot model [...]. Or: I'm unable to
provide the use case [...].

There are a number of advanced use cases for working with consignments (see also [this discussion](https://www.opentripmodel.org/discuss/6123bb8cb2288b00231fbda8)).
* A requested consignment is oversized and cannot be transported as one. Thus the solution is to split the original consignment into multiple smaller consignments which will be transported by different vehicles at different times.
* Something went wrong and part of the goods could not be delivered (for example they are damaged). There needs to be a follow up consignment with new goods to replace the old goods.

In each of these cases there are multiple consignments that are related together. Currently OTM5 does not properly support linking multiple consignments together somehow.

**Describe the solution you'd like**
What would you like to add or change to the specification? Please be as clear and concise as possible.

The simplest solution would be to add a new field `relatedConsignments` to `consignment` so you can refer to other consignments (that have a different status).

**Describe alternatives you've considered**
Did you try to solve it with the current specification? If so, how? Please be as clear and concise as possible.

The only other possible workaround is to use the external attributes. Otherwise another field could be added that achieves somewhat the same.

**Additional context**

The biggest problem with the proposed solution is that it does not provide a good way to communicate _how_ the relatedConsignments are related. So we might need to add another field on Association, or use a different type of association to add this.

**Comment by thomaskolmans** [comment]
At Transportial we're for this change!

**Comment by bmeesters** [comment]
@thomaskolmans, great, thanks for letting us know! Any ideas on how to describe the relationship between the consignments. E.g. add a new field on association like `role` for actors? Or maybe add a new field `relation` for all types of associations and replace `role`?

**Comment by BobZuidhoek** [comment]
Hi Bas, 

Just some additional context on how we see this happening in our companies nowadays. 

We sell boxed products (flowers/plants) to large retailers. They are packed onto pallets/trolleys. Goods are shipped from our warehouses. We do not perform road transportation ourselves, this is outsourced to road freight companies that have perishables transport (refrigerated transport) as core competency. Orders can be a single pallet/trolley, but orders of 50+ pallets or trolleys are also common. 

The process currently works as follows...

We receive purchase orders from our retailer clients (which are distribution center level orders). We book these orders in as sales orders in our ERP-system. This may look something like: 
 - Product A 500 boxes. 
 - Product B 300 boxes
 - Product C 200 boxes. 
Total 1000 boxes. We also know the pallet loadfactor is 25 boxes per Euro-pallet. So the total volume in pallets is 1000/25 = 40 Euro-pallets. We also know the maximum regular trailer capacity is 33 Europallets. 

Therefore we create 2 consignments in our ERP-system. 
Consignment 1: 
 - Product A 500 boxes. 
 - Product B 300 boxes
 - Product C 25 boxes.
This totals 825 boxes (33 pallets).  
Consignment 2: 
 - Product C 175 boxes.
This totals 175 boxes (7 pallets).  
Note that we do not split the sales order, but we now have 1 sales order and 2 related planned consignments. 

The consignments 1 and 2 are sent to our road freight carrier as bookings (individual transport orders). If the carrier accepts the bookings, we're good to go. 
But it may happen that a request for splitting comes back from the carrier's planning department, something like "please split consignment 1 into 12 and 8 pallets". This is where things get a little dirty: 
 - We now rework consignment 1 in our ERP-system into 2 consignments (let's call these new consignments 3 and 4).
 - We drop the transport order of consignment 1. 
 - We send new transport orders for consignment 3 and 4. 

What you see happening here conceptually, is that an interactive booking process is taking place. From what I witness at our companies, this is a very common process to happen between shipper and carrier. The booking process has an impact on the resulting transport orders. 

I think it makes sense to first have a good look at how these booking processes (and the corresponding back-and-forth-processes) should work in OTM, before jumping into adding a concept such as relatedconsignment.

**Comment by bmeesters** [comment]
Thanks for the extensive details Bob. It definitely helps to look at the different processes to see how we want to change OTM. Though from what I can see the `relatedConsignments` would also help in your process right? I think the main addition is that when a consignment 'evolves' over time into multiple consignments you would want to relate these together right? I cannot really imagine that some consignment is being split into multiple consignments and the party issuing the order cannot relate what used to be to the new situation. But I might be missing something?

If you have any alternative ideas I would gladly hear them.

**Comment by BobZuidhoek** [comment]
Hi Bas,

It probably doesn't matter really, but from the perspective of the carrier the consignments are seen as unrelated. The carrier essentially does not know that we have 1 sales order overspanning the consignments that he knows of. Only we as shipper need to know how things are related. Therefore, we essentially don't tell the carrier of consignments being related. 

I could imagine that you need the relatedconsignments functionality to for example profit from bracketed price agreements (Dutch: staffels). In the case of the example I described, if you would have a beneficial full truckload tariff, you need to add up the volume of the three related consignments to calculate the right price bracket. 
Within our companies, we have removed price bracketing completely, because it usually gets in the way of efficient ordering and invoicing processes. We now just have flat prices per loading metre, and agree prices based on historical transportation volumes. This simplifies processes a lot. 

By the way, do you think our way of working is also as intended for OTM? By that I mean that the booking process is a simple create/delete process of transport orders until things settle?

**Comment by bmeesters** [comment]
> It probably doesn't matter really, but from the perspective of the carrier the consignments are seen as unrelated. The carrier essentially does not know that we have 1 sales order overspanning the consignments that he knows of.

I can imagine something like this being more common.

However, I think the current proposal is good enough because:
1. The new `relatedConsignments` field would be optional. So if a party doesn't know it is not required to fill it. Also for some consignments it would not make sense, since there might not be any related consignments.
2. If a party knows the related consignments but does not want to share them because the receiving party doesn't need to know it is also not required to send them. Tackling the case above.
3. It is a easy change, just one optional field consisting of data types already available in OTM5 (associations and consignments).
4. There is currently no alternative to model consignments changing over time and relating them to their previous versions.

If there are any oversights I might be missing I gladly hear them. We will also check with some other parties if they have an opinion on this.

> By the way, do you think our way of working is also as intended for OTM? By that I mean that the booking process is a simple create/delete process of transport orders until things settle?

Yes, I think your modelling makes sense. If consignment 1 cannot be transported by the carrier there are only two options that I can see:
1. Mutate the consignment 1 and create a new consignment 3 (assuming 2 already exists)
2. Cancel consignment 1 and create new consignments 3 & 4 (your current model).

IMO the second one is cleaner since you can more easily keep an audit trail of what happened. **if** we add the `relatedConsignments` it would also become easier to see what ultimately happened with consignment 1 (internally, or with parties that care). But again, you would not be required to if it is not necessary.

**Comment by BobZuidhoek** [comment]
Hi Bas, 

OK thanks. Good to see we're on the right track then. 

I was pondering about this over the weekend and this question came to mind: if now the relatedConsignments concept is going to get its place within Consignments, what is then still the functional use of the TransportOrder layer in the top op the tree? It seems the TransportOrder is losing its value, for example:

1. - A TransportOrder groups together 1 or more Consignments. But that's probably done better using relatedConsignments. By using relatedConsignments, this also ensures a Consignment is **_understood_** as a fully independent object and essentially has nothing to do with the overarching TransportOrder. The Consignment is probably already meant to be a fully independent object, but when you think in actual messages, I can foresee a lot of misinterpretation of happening here around TransportOrder (e.g. there is 1 Transportorder with 3 Consigments and the shipper wants to update only consignment 2, then he wrongly issues a whole update of the Transportorder with all 3 consignments, leading to confusion at the Carrier company) . 

2. - The actors can be set top-level on TransportOrder. But they can also be set sub-level on Consignment. What is the benefit of doing this in the top-level TransportOrder? Is it just efficiency, so you don't have to mention them in Consignment? What happens if you would specify different actors in 1 of the Consignments than as specified in the TransportOrder (would that even be allowed)? Would it not be simpler if you only allow actors on Consignment? 

3. For Constraint, the question is essentially the same as question 2.

In your opinion, is there still any business value left of having the TransportOrder overarch Consignments? My opinion would be that if there is no logical place for TransportOrder anymore, that it should be scrapped. It would only create an expensive layer that needs to be built and dealt with in many systems. 

Maybe others can also chime in on business scenario's they encounter how this is being used.

**Comment by bmeesters** [comment]
This is a good question. In principle the `TransportOrder` makes it easy to send a _bulk_ request, where a party can send all consignments that need to be transported (and might be billed together for efficiency). In that sense it is different from the `relatedConsignments` in that the latter is only meant to link consignments that have a very strong relation, for example because one consignment is succeeding the other (the goods are split, like the earlier examples). On the other hand, the consignments within a `TransportOrder` do not have to be related at all, they are simply 'grouped', which is similar but there is a subtle difference.

That said, I am sympathetic to your point of view. Because the ultimate goal is to make processes standardized and avoid confusion. If parties are going to use OTM5 differently, the benefit of using a standard is diminished.

I think that there is still a need to simply group things together without creating a strong connection, and thus that the `TransportOrder` needs to keep existing, even with the proposed change of `relatedConsignments`. That said, the more OTM5 grows the more the need arises to get clear rules about how OTM5 should be used. For example, currently it is indeed not clear where actors belong, on the `Consignment` or on the `TransportOrders`? Indeed, the general rule of thumb was to have the shared actors on `TransportOrders` (e.g. the issuer of the consignments) and the specific details in the `Consignment`s (e.g. the exact location where each consignment should go to). But I think we should become more clear, potentially at the cost of being more verbose.

So before we continue with this approach it might be good to make those rules upfront and document before introducing a new concept. Though I think we need some more time to think about that (any suggestions for rules are welcome).

**Comment by BobZuidhoek** [comment]
Hi Bas, 

You probably can guess my opinion on this already :-). 

I think it is in this case indeed best to remove the 'duplicate' layer Actors and Constraint from Transportorder. And just maintain everything directly in Consignment. This is then 100% clear for everyone, prevents having to check/solve for inevitable inconsistencies between TransportOrder and Consignment and saves having to build additional parent/child logic into software. 

Can you check with the DALTI community how TransportOrders are being used nowadays? To see whether there is some actual valid business reasons why you want to use the TransportOrder layer? 
For example, invoice grouping would not be a strong argument in my opinion. To my best knowledge, all roadfreight carriers want to get rid of complex invoice summary logic their shippers ask them to perform. As long as the consignment references are maintained, shippers should be able to effectively marry the carriers invoice lines to their own freight purchase order IDs. 

If you would in the end conclude that TransportOrder is just 'legacy' logic to mimic the situation where shippers could send 1 large XML file with many consignments in it (for network efficiency), then keeping that legacy alive goes against the principle of REST. The basic REST-situation should remain that 1 TransportOrder/Consignment (if we merge these concepts into 1) = 1 API-call. This could lead to many 100's or 1000's of API-calls, but that should still be manageable. 
If there would still be a real need for batched API-operations, I think the TransportOrder/consingments in the batch then still each need to be processed in isolation (i.e. we should be wary of logic like "if 1 object fails then the whole batch must fail"). 
This is a bit of an odd website https://diegosucaria.info/handling-batch-operations-with-rest-apis/, but I'm charmed with how the paragraph Create a new batch endpoint and then particularly the idea of POST /batch/users works. The idea of having dedicated API endpoints for batch operations makes sense to me (and keeps the solution clean from the regular true REST endpoints). The example should be improved with a proper batch-ID and ID's for each line in the array, but you get the point.

**Comment by bmeesters** [comment]
> Can you check with the DALTI community how TransportOrders are being used nowadays?

We started out with a beta version of OTM5 that did not have the `TransportOrder`, and almost all parties involved (with many representatives in DALTI) explicitly wanted to include it. So including it seems like quite a big boon for OTM adaption. Whether or not this is a valid enough reason from a technical point of view might be questionable, but I think removing it now would be 'political suicide'. OTM is already somewhat controversial with certain decisions that you can argue are better, but still seem to hinder adoption (see also https://github.com/opentripmodel/otm5-change-requests/issues/29). We can discourage it's use maybe, but I don't think we can remove it. Integrating in current work processes is essential for adoption, even if these processes can be somewhat outdated.

> I think it is in this case indeed best to remove the 'duplicate' layer Actors and Constraint from Transportorder.

We cannot remove fields without bumping the OTM version to 6. But we can deprecate and discourage it until the time is right to make the next jump. In any case should we provide more clear rules on how to use these constructs.

I made a 'change request' for the documentation regarding the subject https://github.com/opentripmodel/otm5-change-requests/issues/34. Because how to deal with `TransportOrder` and `Consignment` actors and constraints is in a sense an orthogonal concern to whether or not to add `relatedConsignments`.

To be clear (what might get lost in conveying over text), I do really appreciate the critical questions and suggestions. This is what helps OTM5 improve and grow over time. So thanks @BobZuidhoek and please continue doing so!

**Comment by thomaskolmans** [comment]
Over the weekend I have thought about this but I would very much urge to keep TransportOrder in place, even with the related Consignments. For administration purposes and ease-of-use I believe that having a base-line of `TransportOrder` will simplify and unify a lot of the data being transferred. The structures that can and will be created if a `Consignment` is also the `TransportOrder` with `relatedConsignments`. 

In version 4 of OTM it was this way and created quite a few complexities these where taken away with the TransportOrder.

**Comment by thomaskolmans** [comment]
Yes I do know that and yes we've based our TMS on OTM, so I am speaking from that perspective. However, I have worked wherein data standards are already widely implemented. In order to easily maintain a data standard and to easily communicate, it should be able to adhere to general concepts within dataflows. 

Even in a perspective of using it as a communication layer I still believe my argumentation holds true. You'll have to communicating some way all possibilities. I believe if you let go of TransportOrder, you lose the base reference point in my opinion. Also in "just" transferring data.

**Comment by bmeesters** [comment]
Great to see this open discussion. If I need to update any information on the documentation (either the developer portal or the API docs) just let me know.

For now, the overall change (related consignments) has been accepted for OTM5.3

**Comment by etwobben** [comment]
hi @bmeesters ! I would like to implement this feature request it advance as we kinda need it now :-) Is there already an consensus on how the model is going to look like? As far as I know there was some doubt about the `relation `field in an asscocation.

**Comment by bmeesters** [comment]
Hello @etwobben I have to admit I forgot a bit about the `relation` field. Though, now having given a bit more thought again I think it makes sense to add it. For a lot of associations the relation is pretty obvious (the actions below a trip, the vehicle on the trip, the consignment under a load or unload, etc.). However for relatedConsignments (like actors) it might not be obvious (e.g. which one is supersedes which and why).

However I am not sure what would be the best relation types to add (initially). Do you need the `relations` field and do you have any suggestions that need to be there?

**Comment by etwobben** [comment]
The `relation` is something we need to describe the reason why something is related. For now I can only think about these; 

- `split`, for consigments that are oversized for example.
- `postponed`. this is for consigments who can't be delivered (partially delivered) and a new consigment is created with a new delivery date.

The `description `field in a association can be used for some more information.

**Comment by bmeesters** [comment]
Sounds good to me. We can always add more `relation` types in future OTM versions if the need arises.

**Comment by bmeesters** [comment]
This has been implemented in OTM5.3 released today and thus can be closed.
