### ISSUE TITLE
Inconsistent naming: timeWindowConstraint vs timeWindowsConstraint 

### ISSUE THREAD

**Issue by rverberne** [opentripmodel/otm5-change-requests#33]
**Type of bug**
- [X] Inconsistency or contradiction in the specification
- [ ] Fault in the representation (rendering) of the specification
- [ ] Other (please describe below)

**Describe the bug**
 - The text says "_Since OTM5.2 the **timeWindowConstraint** is supported which allows you to..._"
 - The spec and changelog says "**_timeWindowsConstraint_**". (with additional s)

So wich one is it? Plural `windows` or singular `window`?

**Comment by bmeesters** [comment]
Thank @rverberne,

It should be singular, since the constraint can only model a single interval, which is what a time window is. I'll update the relevant documentation.

**Comment by bmeesters** [comment]
I fixed it, it is not the singular form everywhere.
