### ISSUE TITLE
Improve OTM5 documentation w.r.t. on where to use actors and constraints (in consignments/transportOrders)

### ISSUE THREAD

**Issue by bmeesters** [opentripmodel/otm5-change-requests#34]
OTM5 has some flexibility how to structure certain messages. For example it is possible to add the shipping and carrier parties on the `TransportOrder` level or the `Consignment` order level. The general unwritten rule was that you avoid duplication, so if an actor is used multiple times you use it on `TransportOrder` and if it is unique for a single `Consignment` you use it there. However, this approach is not scalable and becomes inconsistent if the content of the messages start to change. See also the discussion in https://github.com/opentripmodel/otm5-change-requests/issues/32. A similar problem exists for the actors on a trip.

To avoid confusion and become consistent OTM5 should make clear rules and document those.

**Comment by BobZuidhoek** [comment]
Hi Bas, 

Could you 'stretch' the subject of this issue to to also include documentation of functional reasons when to use 1 TransportOrder with 1 or multiple consignments? 

The functional logic behind that probably automatically translates into how to use actors and constraints on each level.

**Comment by bmeesters** [comment]
Going over all the open change requests again, sorry this has been delayed for a while. I will do this before the next release. So I'll just add the release tag

**Comment by bmeesters** [comment]
I have updated the documentation to reflect the situation
