### ISSUE TITLE
Add `unCode` to `Location` 

### ISSUE THREAD

**Issue by thomaskolmans** [opentripmodel/otm5-change-requests#36]
**Type of request**
- [x] I'd like to add something to the OTM 5 spec

**Describe the solution you'd like**
Would like to have `unCode` added to the `Location`. Description of the unCode: UN/LOCODE; the United Nations Code for Trade and Transport Locations of the location

**Describe alternatives you've considered**
`externalAttributes` but in our believe that should not suffice.

**Comment by bmeesters** [comment]
This has been implemented in OTM5.3 released today and thus can be closed.
