### ISSUE TITLE
Add TemperatureCelsius as contraint type enumeration value

### ISSUE THREAD

**Issue by BobZuidhoek** [opentripmodel/otm5-change-requests#37]
I'd like to add something to the OTM 5 spec.

**_Background / context_**
In the perishables and refrigerated transport industry, it is very common to specify a minimum, maximum or range of temperatures that a consignment must be transported in. Currently, there is no explicit Constraint>Value>Type for TemperatureCelsius. 

My opinion is that a temperature constraint is so common, that it deserves to have its own type. The type SensorValueConstaint or GenericContraint does not quite cut it. 

**_Describe the solution you'd like_**
 - Add TemperatureCelsius to Constraint>Value>Type enumeration
 - Have the same setup as currently for weightConstraint (i.e. maximum, minimum, range). 

**_Additional context and considerations_**
I think that we do not have to make it that flexible so you can specify the temperature type (Celsius, Fahrenheit or Kelvin). Fahrenheit is only used in the United States. Kelvin is more for scientific purposes.   

I do not know if it should be allowed that 2 goods-lines in 1 consignment could be transported at 2 different temperatures (e.g. the frozen fish must be transported below -5 degrees and the fruit between 5 to 10 degrees). I presume a scenario like that is, also from a legal perspective, best handled using 2 separate consignments (and 2 different CMR's). I hope other people can comment on how this works.

**Comment by bmeesters** [comment]
This has been implemented in OTM5.3 released today and thus can be closed
