### ISSUE TITLE
Strengthen enforcement of Role of Consignment Actors

### ISSUE THREAD

**Issue by BobZuidhoek** [opentripmodel/otm5-change-requests#38]
I'd like to change something in the OTM 5 spec.

**_Background / context_**
In a consignment, multiple actors play their part. These actors have a role. Currently in OTM5, a consignment contains an array of actors (1 or more) . Then, it is OPTIONAL to specify the actor their role(s) (1 or more). 

Having an actor for which no role is mentioned, seems unlogical. System-wise, you can't do anything with an actor for which it is not clear what their role is. Specifying a role of an actor should be mandatory. 

Another observation is that some roles should technically only be performed by 1 actor. OTM5 currently gives technical freedom to make errors here (e.g. have 2 actors play the role of shipper). 

**_Describe the solution you'd like_**
I propose 2 solutions (1 is soft, 1 is tougher and stronger). 

The first (soft) solution is that it should become mandatory to specify at least 1 role for every actor in a consignment. 

The additional "bonus" for the first (soft) solution would be that the OTM5 standard should specify and technically check which roles are allowed to be fulfilled by only 1 or multiple actors. 

The second (tougher and stronger) solution could be that the datamodel is changed from "Consignments 1:n Actors 1:n Roles" to "Consignments 1:n ActorRoles 1:n Actors". This also the way UBL did it. In such a case, it is easier to specify and check which ActorRoles are allowed to only have 1 actor. 

**_Describe alternatives you've considered_**
The current OTM specification works, but I feel that this is a weak area that could lead to unnecessary implementation difficulties. 

**_Additional context_**
If others feel that a Role is missing, then we should discuss and add these. Not having a certain Role available should not be a valid reason to wanting to keep Actors unspecified of their Roles.

**Comment by bmeesters** [comment]
I will add it do the API specification next release
