### ISSUE TITLE
Improve the Consignment.status concept (part 1): be able to communicate consignment data (in-)completeness

### ISSUE THREAD

**Issue by BobZuidhoek** [opentripmodel/otm5-change-requests#39]
I'd like to change something of the OTM 5 spec.

**_Background_**
Currently a "Consignment"."status" attribute exists, with currently these enumeration values:
 - draft
 - requested
 - confirmed (this replaces accepted)
 - inTransit
 - completed
 - cancelled

Looking at these statuses, they actually describe the status of different (independent) lifecycles. For example: 

1. If all basic data of the consignment is complete for the consignment to be executed: status draft exists, missing status: final.
2. What the status of the administrative booking process is: status requested, confirmed (formerly accepted) and cancelled exist, missing: rejected 
3. What the main transportation execution status is: status inTransit and completed exist. Others are missing. 
4. There could be other process statuses, such as invoicing-status or payment-status.

For efficient discussion, I'll make a Github issue to discuss my suggestion improvement on each status lifecycle. First subject: consignment data completeness. 

**_Introduction_**
A shipper sends OTM5 TransportOrders/Consigments to a carrier. It may be the situation that, for pre-advising the carrier as early as possible for what is coming, shippers send consignment data that is not yet complete (e.g. because the rough volume is known but not yet fully specified into goods, not all actions are completely known, etc). 

It is important for a carrier to know if the basic transport order data of a consignment is considered complete or if the carrier should still expect an update on it. To make this clear, we need an atrribute on Consignment, something along the lines of "ConsignmentBasicDataCompleteness". The attribute has an enumeration of "draft" and "final". 

How the process then works: 
The shipper can create a consignment with status "draft" (if he's aware that it's not fully completed). The shipper can send an update (PUT api-call) later and update the consignment with new information. Even after the update, the status can still remain "draft" (if it's an inbetween update). On the final update (PUT api-call), the shipper sets the status to "Final". 

Of course, the shipper can set the status to "Final" on the first api-call if the consignment is considered complete in the first call.  

Only consignments that have a "ConsignmentBasicDataCompleteness" "Final" status, can be taken into execution by the carrier. 

**Describe alternatives you've considered**
I'm not really sure of an alternative how a shipper can signal the carrier that the data is (in)complete if we would not have the attribute "ConsignmentBasicDataCompleteness". 

**Additional context**
Additional scenario that may be solved with this as well: many large shippers send some form of forecast transport orders to their carrier. This is just for rough capacity planning reasons performed by the carrier. The carrier can use consignments with "ConsignmentBasicDataCompleteness" "Draft" for forecast planning scenario's as well.

**Comment by thomaskolmans** [comment]
Is this not why there is the status `confirmed`?

**Comment by bmeesters** [comment]
In principle yes. `draft`, `requested` and `confirmed` are the statuses that are used in the initial process of creating a consignment and communicating it with other parties.

For me the bigger question is whether we want multiple status fields (see also https://github.com/opentripmodel/otm5-change-requests/issues/43). Personally I don't see the need, but I have to admit that I am generally more involved with trip execution than the consignment creation.

If you have an opinion on whether or not multiple status fields are sensible I would appreciate it if you can share your views on the subject on that ticket.

**Comment by thomaskolmans** [comment]
Personally don't see the need, nor do I understand the need honestly. So that might be a limitation on my end - but in my eyes a `Consignment` only exhibits 1 status. We're very much open to more status options, also to more status-types but from our perspective we don't see the need.

**Comment by bmeesters** [comment]
I want to revive this discussion again. I personally also do not see the need. A consignment always is in a single status, multiple status fields would indicate that it it in multiple statuses at once. It would also require some rules. Like do subsequent processes that have a status field require that previous status fields are filled in? What do to with status fields that are inconsistent with each other.

@BobZuidhoek do you have any remarks on this? Or parties of whom you know use it like this (potentially with some internal format) and why? Otherwise I am inclined to close it.
