### ISSUE TITLE
TransportEquipmentTypeConstraint

### ISSUE THREAD

**Issue by thomaskolmans** [opentripmodel/otm5-change-requests#46]
**Type of request**
- [x] I'd like to add something to the OTM 5 spec
- [ ] I'd like to change something in the OTM 5 spec

**Is your feature request related to a problem?**
Not able to create a constraint for a TransportEquipmentType

**Describe the solution you'd like**
A new `ConstraintValue` type namely `TransportEquipmentTypeConstraint` with an array of possible types. Just like `VehicleTypeConstraint` and `FuelTypeConstraint` are constructed. 

So a `Constraint` with that type it will look something like: 
``` json
{
   "name": "Name of constraint", 
   "value": {
       "type": "transportEquipmentTypeConstraint",
       "transportEquipmentTypes": ["trailer"]
   }
}
```

**Describe alternatives you've considered**
None -  don't see a valid alternative to be honest.

**Comment by bmeesters** [comment]
Hello Thomas, thanks for your contribution again. I will discuss it, but I also don't really see an alternative. Though note that everything for OTM5.3 is closed since we are going to release it next week and this will not have had enough time for others to provide alternatives or counter arguments.

**Comment by bmeesters** [comment]
Hello @thomaskolmans, we discussed it and it makes sense to add this constraint. If possible, can you elaborate how you would use this addition? Is this for transport orders? For trips that need some trailer? I also assume we also want to leverage `equipmentSubType` so you can indicate what kind of trailer(s)?

**Comment by thomaskolmans** [comment]
This is for `Consignment` and `Trip` maybe even `Location`. Yes, the `equipmentSubType` would also come in handy
