### ISSUE TITLE
Documentation does not show Action and Document in AssociationCreatedEvent

### ISSUE THREAD

**Issue by rverberne** [opentripmodel/otm5-change-requests#54]
**Type of bug**
- [X] Inconsistency or contradiction in the specification

**Describe the bug**
In de documentation for `associationCreatedEvent`, `entity1` and `entity2` inline associations do not show `action` or `document`. So you cannot use this event to signal a `Document` created for a `Action`. Is this a oversight?

**Comment by bmeesters** [comment]
Hello @rverberne, this indeed has been an oversight. I will fix it before the next release.
