### ISSUE TITLE
Support a description field on constraint types

### ISSUE THREAD

**Issue by jeroentervoorde** [opentripmodel/otm5-change-requests#56]
**Type of request**
- [X] I'd like to add something to the OTM 5 spec
- [ ] I'd like to change something in the OTM 5 spec

**Is your feature request related to a problem?**
I need to be able to add multiple types of time window constraints on a stop some way to determine the type of window.

**Describe the solution you'd like**

Support a description (or name) field to the constraint. For instance:
```
{
  "type": "andConstraint",
  "and: [
    {
      "description": "block times"
      "type": "timeWindowConstraint",
      "startDateTime": "2021-06-23T10:00:00.000Z",
      "endDateTime": "2021-06-23T13:00:00.000Z",
    },
    {
      "description": "alert thresholds"
      "type": "timeWindowConstraint",
      "startDateTime": "2021-06-23T09:45:00.000Z",
      "endDateTime": "2021-06-23T13:15:00.000Z",
    }
  ]
}  
```
**Describe alternatives you've considered**

Use a "windowType" attribute instead of description. This will likely be very implementation specific. Also this same approach can also be used to specify a constraint on the start (or end) time using a {"type": "startDateTimeConstraint"}

**Comment by bmeesters** [comment]
After discussion we decided to add this to all constraint types. In the future we might add a list of common descriptions as enum, but for now it seems too open to create one.
