### ISSUE TITLE
Add a TravelDistanceEvent

### ISSUE THREAD

**Issue by bmeesters** [opentripmodel/otm5-change-requests#58]
**Type of request**
- [x] I'd like to add something to the OTM 5 spec
- [ ] I'd like to change something in the OTM 5 spec

**Is your feature request related to a problem?**
OTM5 already supports events coming from devices related to fleet management systems, such as the temperature in a truck (frozen or cooled goods) and GPS updates to indicate where the vehicle is driving. However, there is currently no way to communicate what distance is (planned/projected/realized) traveled. This information is often needed for billing and shared among parties. 

**Describe the solution you'd like**

A new event, for example named `TravelDistanceEvent` that contains the distance traveled in a specific lifecycle. The event can also optionally contain the corresponding move action to provide the from/to locations and the route used. Alternatively the fields from, to and route are also optionally available on the new event.

**Describe alternatives you've considered**
You can achieve almost the same by adding a `distance` field on the `move` itself and use those moves in the trip/consignment. This is a smaller change, but not reusable for FMS parties providing the distance traveled using an event. To compensate for this you can add an `odometer` field to the `LocationUpdateEvent`s.

**Additional context**

**Comment by thomaskolmans** [comment]
Not for this event. As it's not an `event` in the literal sense of the word. At most it would be a `SensorUpdateEvent` which is how we've implemented this actually (an odometer is a sensor to some extend).  

I would see the case for a `odometer` field on the `LocationUpdateEvent`, that makes sense and is valuable information.

**Comment by bmeesters** [comment]
Do you have an alternative that could work?

**Comment by thomaskolmans** [comment]
Yes I would opt for `distance` (in meters or `ValueWithUnit`). This field can be both added in `Trip` and the `Action` with type `move`. Both of these models have already a full lifecycle implemented and can thus show very accurately what has been `planned` (pre-calculated) and then `realized`.

**Comment by bmeesters** [comment]
This is quite dormant and I don't see any demand for it much anymore so I will just close it
