### ISSUE TITLE
Add transportOrder field to Consignment

### ISSUE THREAD

**Issue by rverberne** [opentripmodel/otm5-change-requests#59]
**Type of request**
- [X] I'd like to add something to the OTM 5 spec
- [ ] I'd like to change something in the OTM 5 spec

**Describe the solution you'd like**
Add `transportOrder` field (association) to Consignment.

We would like to be able to send a Trip in one go:

```
Trip
    Stop
        Load
            Consignment
                TransportOrder
```

**Comment by bmeesters** [comment]
This has been dormant for a while, but IMO this is an easy change that is logical if we look how OTM5 is build up compared to how other entities work. I would say we should add it in the next OTM5 version.

**Comment by bmeesters** [comment]
This is now part of OTM5.5
