### ISSUE TITLE
add eori number to contactdetails actor

### ISSUE THREAD

**Issue by woutvandenheuvel** [opentripmodel/otm5-change-requests#60]
**Type of request**
- [x] I'd like to add something to the OTM 5 spec
- [ ] I'd like to change something in the OTM 5 spec

**Is your feature request related to a problem?**

**Describe the solution you'd like**
EORI stands for “Economic Operators Registration and Identification number”.

Businesses and people wishing to trade must use the EORI number as an identification number in all customs procedures when exchanging information with Customs administrations.

Having one common type of identification number across the EU is more efficient, both for economic operators and customs authorities.

It is also more efficient for statistical purposes and security purposes

**Describe alternatives you've considered**

**Additional context**
Format of the EORI number
The EORI number exists out of two parts:

the country code of the issuing Member State; followed by
a code or number that is unique in the Member State

**Comment by bmeesters** [comment]
@woutvandenheuvel what to do with this? It seems easy enough to add. Is there any demand from the domain though?

**Comment by woutvandenheuvel** [comment]
@bmeesters It is used in international trade and used by customs. It is also used as an identifier within iSHARE.

**Comment by bmeesters** [comment]
This is now part of OTM5.5
