### ISSUE TITLE
EURALCODE in OTM5

### ISSUE THREAD

**Issue by wzentjens** [opentripmodel/otm5-change-requests#64]
At the moment the EURALCODE is not yet available in the latest version of OTM. It could be a good and logical addition.

Info:

https://sutc.semantictreehouse.nl/api/v1/uploads/FileObject_1527195075_00087938/140204%20EBA%20standaard%201.1%20definitief.pdf

**Type of request**
- [x] I'd like to add something to the OTM 5 spec
- [ ] I'd like to change something in the OTM 5 spec

**Is your feature request related to a problem?**
For CBS roadtraffic survey it would be a valuable addition.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Michiel-s** [comment]
Make sense to me as well. Waste classification using EURAL is also part of the [EBA standard](https://www.sutc.nl/elektronische-begeleidingsbrief-afval) in the transport document message [Eural code element](https://sutc.semantic-treehouse.nl/#/TreeView/Element_1589199970_00772477).

Like with commodity classification, SUTC could make the EURAL list available as a taxonoly or flat codelis; like the recently published codelist for [Returnable Transport Items](https://sutc.semantic-treehouse.nl/#/Codelist/Codelist_c4fd67d1-0c6e-4f6e-b304-529047d37c03)

**Comment by bmeesters** [comment]
I personally do not know much about EURAL (also note that the link in the description does not work). How would you like to see this integrated? On what entity/entities?

**Comment by bmeesters** [comment]
We would like a bit more concrete change request. Where does the EURAL code need to go, and what are the valid values. Unfortunately we have limited time, and figuring out all these things ourselves is not on the top of the list of priorities.

If there is an example of how you would the OTM5 to look like we can accept/tweak it. But if not we will close this CR.

**Comment by wzentjens** [comment]
Considering EURAL code is a property of a good, the goods section seems the most logical place. In 'ADR', there is a 'waste' property. If waste = true there should be the possibility to attach an Euralcode, so maybe the waste property should also move to the goods section? That's up to you.

**Comment by Michiel-s** [comment]
Because of the OTM profile for waste (EBA), we need to reopen this issue.

EURAL is like the HS classification code a scheme to classify goods, in this case waste. Not necessarily ADR.

My suggestion is to extend the goods items classificationLines object with euralCode. Like so:

```jsonc
classificationLines:
    description: >-
      Product classification information often required at customs. A single
      product can contain multiple classification

      lines. For example whenever the product consists of multiple components
      that can each be classified. The most

      important information in the classification lines is often the HS code.
    type: array
    items:
      type: object
      properties:
        hsCode:
          description: >-
            [The Harmonized System (HS) code](https://en.wikipedia.org/wiki/Harmonized_System) is a product
            classification code used by all members of the World Customs Organization (WCO) to
            classify goods for customs purposes.
          type: string
        euralCode:
          description: >-
            EURAL codes (European Waste Catalogue) are standardized 6-digit identifiers used across the European Union to classify waste. They identify the waste's origin, the industrial process that produced it, and indicate whether the material is classified as hazardous or non-hazardous.
          type: string
        ...
```

**Comment by Michiel-s** [comment]
To be decided by OTM working group to take this issue into account for upcoming OTM 5.9 release
