### ISSUE TITLE
OTM5 swagger.json fails validation in MuleSoft

### ISSUE THREAD

**Issue by florian-baltes-nextview** [opentripmodel/otm5-change-requests#66]
**Type of bug**
- [ ] Inconsistency or contradiction in the specification
- [ ] Fault in the representation (rendering) of the specification
- [x] Other (please describe below)

**Describe the bug**
The current OTM5-Specification can not be imported into MuleSoft as it fails the built in validation in three different places: 

Line | Error
-- | --
`9894` | Error: 'eventType' is duplicated in 'required' property
`13727` | Error: 'eventType' is duplicated in 'required' property
`26670` | Error: Name Bearer token does not match regular expression `^[a-zA-Z0-9\.\-_]+$` for component declarations

**To Reproduce**
1. Try to published the imported OTM5 swagger.json file
2. See validation errors

**Expected behavior**
Validation for OTM5 swagger.json file should pass

**Screenshots**
n/a

**Technical information (only if the bug is a fault in the rendering)**
 n/a

**Additional context**
n/a

**Comment by florian-baltes-nextview** [comment]
MuleSoft validates the OTM5 swagger.json file after I performed the following operations on it: 

* removed line 9894
* removed line 13727
* replaced `"Bearer token"` with `"bearer_token"` over the whole document (basically renaming the Bearer token security scheme to match the regex in the error)

**Comment by bmeesters** [comment]
Hello @florian-baltes-nextview, thanks for your contribution. I do have a few follow up questions:
* In line 9894, do you mean the whole example? If so, do you know what is wrong, we need to render examples so we cannot just remove it.
* with line 13727, do you mean format: double? If so, what is wrong with it?
* Seems reasonable to replace.

**Comment by bmeesters** [comment]
Thanks, I downloaded the file from this repository, but it seems those are not in sink. I'll see if I can get rid of the duplicate lines. Note that the swagger is generated, so it is not that easy to just remove them since then we have to check it every time we make a change again. Any way, this is worth fixing, cannot promise yet when though.

**Comment by florian-baltes-nextview** [comment]
Thank you @bmeesters. there is no time criticality for me here as I fixed those lines myself. I just thought its worth mentioning :)

**Comment by bmeesters** [comment]
Alright good to know! And thanks for bringing it up, always nice if people help getting OTM5 better! I'll keep the issue open until it is actually fixed so you get a notification whenever that happens.

**Comment by bmeesters** [comment]
Since Mulesoft is closed software we will close this issue. We will take into account the feedback we got regarding duplicate discriminators and separate strings for the next version though to avoid the problems where possible.
