### ISSUE TITLE
Road closures

### ISSUE THREAD

**Issue by filogic** [opentripmodel/otm5-change-requests#69]
**Type of request**
- [x] I'd like to add something to the OTM 5 spec
- [ ] I'd like to change something in the OTM 5 spec

**Is your feature request related to a problem?**
Currently, there is no consistent way to describe road closures (e.g. in routes).  This is a problem when describing planned - or actual road works.  Route optimisation engines and planning systems should be able to take into account that a route is (temporary) closed, so it can determine an alternative route.

**Describe the solution you'd like**
Introduction of a new constraint type named **accessConstraint** which has an enum property describing the accessability of the road: `partialClosed`, `closed`, `open` as depicted below:

```
{
  "type": "accessConstraint",
  "access": "closed", 
  "description": "2 lanes closed"
}
```
Note that "access": "open" is the same as not having this constraint at all, so this option might be superfluous.

**Describe alternatives you've considered**
A solution is to use a generic constraint for this:
```
{
  "type": "genericConstraint",
  "access": "road closed"
}
```
However, this solution is not able to feed route optimisation engines and planning systems correctly as it does not restricts access to this specific road.

**Comment by bmeesters** [comment]
Thanks for making one so quickly! I think the current proposal is as discussed and good to add.

**Comment by bmeesters** [comment]
Discussed and accepted for OTM5.5

**Comment by bmeesters** [comment]
This is now part of OTM5.5
