### ISSUE TITLE
Question: Associated routes for trips and linked vehicles

### ISSUE THREAD

**Issue by Jxlle** [opentripmodel/otm5-change-requests#70]
Hi,

I was looking through the documentation of the OTM v5 model and in the [trip entity section](https://www.opentripmodel.org/docs/trip-entity#) of the guide, it is explained that route entities can be associated with a trip. However, I have difficulty finding where in the API this is possible, as there is no _route_ property anymore for [creating a trip entity](https://otm5.opentripmodel.org/#tag/Trip/paths/~1api~1v5~1trips/put). Am I missing something?

I have a similar question for [vehicle entities](https://www.opentripmodel.org/docs/vehicle-entity). The guide explains that vehicles can be linked using the _links_ property, but I cannot find this in the [API spec](https://otm5.opentripmodel.org/#tag/Vehicle/paths/~1api~1v5~1vehicles/put).

EDIT: Is an [AssociationCreatedEvent ](https://otm5.opentripmodel.org/#tag/Event) used for this instead? 

Regards

**Comment by bmeesters** [comment]
Hello @Jxlle, you are right, this is currently not well explained. At the moment you can attach a `route` to a `move` action. Moves actions can thus be part of a `trip` entity. This means that it is currently possible to attach routes to the sub-parts of a trip, by having routes from each individual location to the next. However it is thus not possible to attach the complete route to a trip.

I'll be sure to update the documentation. If there is a need to also attach `route`s on the trip itself you would need to create a change request.

**Comment by Jxlle** [comment]
Thank you, it is clear now!

**Comment by bmeesters** [comment]
I removed some OTM4 pages since they are confusing, the current documentation should make it more clear
