### ISSUE TITLE
Properties and classes have identical names

### ISSUE THREAD

**Issue by huibertalblas** [opentripmodel/otm5-change-requests#71]
**Type of request**
- [ ] I'd like to add something to the OTM 5 spec
- [x] I'd like to change something in the OTM 5 spec

**Is your feature request related to a problem?**
With the current specification i cannot convert an OTM json file to an OTM json-ld file by just appending a [@context](https://www.w3.org/TR/json-ld11/#the-context) section.

**Describe the solution you'd like**
Currently properties and classes can have identical names within OTM. For example: 'stop' is both an [actionType](https://otm5.opentripmodel.org/#tag/Action/paths/~1api~1v5~1actions/put!path=2/actionType&t=request)/entityType, aswell as a [property](https://otm5.opentripmodel.org/#tag/Action/paths/~1api~1v5~1actions/put!path=0/stop&t=request) under 'Action'.
It would be convenient to differentiate between the two, by starting the class/actionTypes/entityType names with a capital letter.

**Describe alternatives you've considered**
Alternatively an active conversion can be used to rewrite these class names, but the downside to that is:
- it is much harder to implement for an average organisation than just appending a static @context section to a file
- it is more difficult to maintain an active conversion

**Comment by bmeesters** [comment]
Hello @huibertalblas,

Though I understand the need, it would require to change all the entity, stop and event types. This would not be backwards compatible and therefore is not possible in the OTM5.X line. It could be part of OTM6, but I doubt we want to go that route any time soon as it likely halts any momentum we currently have as a standard.

Alternatively we could create all the entity types with double and deprecate the ones with a lowercase, but that would result in a lot of noise in the specification. Also it would require all existing parties to change their implementation as, and potentially future implementing parties as they would need to adopt for the possibility that either the capital or non-capital version is used.

So, in hindsight it could have been better to make the difference more clear, the amount of work it would cost is not worth it. I will leave the change request open so we can discuss it in a larger setting, but I do not think it is viable to make these changes.

**Comment by bmeesters** [comment]
Closing this since we cannot make such drastic changes that would break all existing OTM5 services
