### ISSUE TITLE
Inconsistency in sample data for Trip

### ISSUE THREAD

**Issue by huibertalblas** [opentripmodel/otm5-change-requests#72]
**Type of bug**
- [ ] Inconsistency or contradiction in the specification
- [ ] Fault in the representation (rendering) of the specification
- [X] Other (please describe below)

**Describe the bug**
There seems to be an inconsistency in the sample data. The [request sample](https://otm5.opentripmodel.org/#tag/Trip/paths/~1api~1v5~1trips/put) under 'Trip' contains 2 load actions. Both actions have the same identifier, while their contents are different. (currently both have 'adcd2548-0c2c-4f39-8b4c-317dcbcb9c41')

**To Reproduce**
Visit the [example message under Trip](https://otm5.opentripmodel.org/#tag/Trip/paths/~1api~1v5~1trips/put)

**Expected behavior**
I would expect these two to load actions to have a different uuid. (currently both have 'adcd2548-0c2c-4f39-8b4c-317dcbcb9c41')
Because, the get Actions endpoint only allows to return one Action for a given UUID. Therefore it seems not logical to have a duplicate identifier in one message.

**Comment by bmeesters** [comment]
Yes, good point, I'll be sure to update the documentation! Thanks for bringing it up!

**Comment by bmeesters** [comment]
I might be looking in the wrong place (or it might have already been solved at some earlier point in time). But I do not see any actions with the same UUID. So I think this can be closed? Or did I miss anything @huibertalblas ?
