### ISSUE TITLE
Indicate the degree of obligation or enforceability of a constraint

### ISSUE THREAD

**Issue by filogic** [opentripmodel/otm5-change-requests#75]
**Type of request**
- [x] I'd like to add something to the OTM 5 spec
- [ ] I'd like to change something in the OTM 5 spec

**Is your feature request related to a problem?**
Currently, there is no standardized way to indicate the degree of obligation or enforceability of a constraint. While constraints themselves can be specified and defined, there is no universal method for indicating whether a constraint is a hard requirement that must be followed, or a more lenient recommendation. This lack of clarity can make it difficult for systems to know how strictly they need to adhere to a particular constraint, which can lead to confusion and inconsistency in enforcement. As such, there is a need for a clearer and more standardized approach to indicating the degree of obligation or enforceability of constraints.

**Describe the solution you'd like**
To address the lack of clarity around the degree of obligation or enforceability of constraints, we propose the addition of a new property to constraints called `"enforceability"`. This property would be an enumerated type, with two possible values: 

- "enforced"
- "preference" 

An enforced-constraint would indicate that the restriction is an absolute requirement that must be followed, while a preference-constraint would indicate that the restriction is a recommendation or preference, but not an absolute requirement. 

By adding this property to constraints, we can provide a clearer indication of how strictly a particular constraint needs to be adhered to, which can improve consistency in enforcement and reduce confusion for individuals and organizations trying to follow the restrictions.

The following code-fragment depicts how a hard-constraint can be described in OTM:

```
{
   "id": "89a7bb4d-8720-4db9-aef7-4c3309186c3e",
   "name": "Example hard constraint",
   "creationDate": "2023-03-28",
   "creationDate": null,
   "contextEvents": null,
   "value": { ... },
   "enforceability": "enforced",
   "externalAttributes": null,
}
```
 

**Describe alternatives you've considered**
An alternative for the "enforceability" property could be "constrainLevel" with enum "mandatory", "voluntary":

```
{
   "id": "89a7bb4d-8720-4db9-aef7-4c3309186c3e",
   "name": "Example hard constraint",
   "creationDate": "2023-03-28",
   "creationDate": null,
   "contextEvents": null,
   "value": { ... },
   "constraintLevel": "mandatory", "voluntary",
   "externalAttributes": null,
}
```

**Comment by bmeesters** [comment]
I am all in favor of this change. Let's discuss it during the next meeting we have

**Comment by bmeesters** [comment]
Discussed within the group and all are in favor. Question that did pop up is where OTM ends. Since we are gradually increasing more map related data

**Comment by thomaskolmans** [comment]
RFC 2445 iCal specificatie: https://www.ietf.org/rfc/rfc2445.txt

**Comment by bmeesters** [comment]
Accepted. If the field is not present it should be interpreted as mandatory to ensure backwards compatibility.

**Comment by bmeesters** [comment]
This is now part of OTM5.6 so can be closed.
