### ISSUE TITLE
Move action sequenceNr to support multiple sequences

### ISSUE THREAD

**Issue by SytseOegema** [opentripmodel/otm5-change-requests#79]
- [ ] I'd like to add something to the OTM 5 spec
- [x] I'd like to change something in the OTM 5 spec

**Is your feature request related to a problem?**
We want to track the sequence of actions inside different entities. Currently an action contains a `sequenceNr` which can be used to defined the sequence number of the action with the parent entity. This is a great feature we are already using to determine the sequence of stops and substops within a trip. We also want to use the sequence number for ordering load and unload actions within a consignment. But that is not possible because we store an action in the database which is associated with both a Trip and a Consignment.

So we want to define multiple sequences for the same action.

**Describe the solution you'd like**
For us the problem would be solved if the sequence number of an action is stored in the association of the action instead of in the action itself. That makes it possible to define a sequence for actions within each parent entity. Consider the example JSON below. This would also make it possible to define other sequences of actions in other parent entities.

```
{ // trip
  "actions": [
    {
      "associationType": "inline",
      "sequenceNr": 1
      "entity": {
        "id": "action1"
      }
    },
    {
      "associationType": "inline",
      "sequenceNr": 2
      "entity": {
        "id": "action3"
      }
    }
  ]
}

{ // consignment 1
  "actions": [
    {
      "associationType": "inline",
      "sequenceNr": 2
      "entity": {
        "id": "action1"
      }
    },
    {
      "associationType": "inline",
      "sequenceNr": 1
      "entity": {
        "id": "action2"
      }
    }
  ]
}

{ // consignment 2
  "actions": [
    {
      "associationType": "inline",
      "sequenceNr": 1
      "entity": {
        "id": "action3"
      }
    }
  ]
}
```

**Describe alternatives you've considered**
At this moment in time we are not aware of any solution that supports this within OTM. It could of course always be communicated within the externalAttributes, but we deemed this important enough to submit.

**Comment by thomaskolmans** [comment]
I'm against this change for the following reasons: 

1. It introduces ambiguity in my opinion
2. OTM is a data-communication model, not a database model in and of itself. Thus the issue that you flagged is a database-design problem, not necessarily a data-communication one

Also I've tried to imagine why this can cause an issue. Let's say a that the `sequenceNr` changes, why is it bad that it changes on both levels? Isn't that a good thing?

**Comment by bmeesters** [comment]
Hello @SytseOegema, thanks for your contribution. I understand the concern and that it is not possible with the current specification. However, I also think that having the same field in two places can be very confusing. 

Personally I believe the sequenceNr is a bit redundant because you can use both
1. The order of the actions in the list of actions itself.
2. Use the chronological order based on the start/end time of the actions. 

So, IMO, I don't think it would be wise to add it since it is confusing and order can still be determined. We will need to discuss it with the group though. @woutvandenheuvel could you pick this up once the group is complete again?

**Comment by bmeesters** [comment]
Since it can be confusing and there are alternative methods, this will not be added to OTM
