### ISSUE TITLE
Improve documentation on time windows

### ISSUE THREAD

**Issue by BenKrocke** [opentripmodel/otm5-change-requests#8]
**Type of request**
- [ ] I'd like to add something to the OTM 5 spec
- [x] I'd like to change something in the OTM 5 spec

**Is your feature request related to a problem?**
The current documentation is lacking in explaining the difference between the time window in Action, and the time window in (TransportOrder) Constraint.

**Describe the solution you'd like**
Improve the explanation of both properties so that it becomes clear what their purpose is and what differentiates the two.
Another option would be to provide example situations in the documentation, so that it becomes easier to place entities/properties into context. (I.e. the scenario Bas presented in the forum topic was helpful for me to understand the difference) 

**Describe alternatives you've considered**
N.v.t.

**Additional context**
[Discussion forum topic](https://www.opentripmodel.org/discuss/605b17307b810d0072737ffb)

**Comment by bmeesters** [comment]
Hello Ben, thanks for your contribution. We will update the API documentation soon to improve it. I agree the current documentation is indeed lacking.

Note that 'behind the scenes' we are working on a developer portal with more examples and explanations as addition to the API documentation, I'll be sure to add the scenario you found helpful as well.

**Comment by bmeesters** [comment]
Hello @BenKrocke, we started creating a developer page and I added a small section on Constraints. Note that this is all still very much a work in progress. But I wanted to show you that we appreciate the feedback and take it seriously. Here it is: https://otm5developerportal.redoc.ly/developer-portal/constraints/. It will be enhanced in the coming weeks with more examples, etc.

**Comment by BenKrocke** [comment]
Hi @bmeesters, thanks for letting me know. Looks great!

**Comment by bmeesters** [comment]
The OTM5 portal is now broader shared, so this can be closed.
