### ISSUE TITLE
Validation endpoint for transportOrders profile not checking the constraints

### ISSUE THREAD

**Issue by Michiel-s** [opentripmodel/otm5-change-requests#83]
**Type of bug**
- Inconsistency or contradiction in the specification
- Fault in the representation (rendering) of the specification
- [x] Other (please describe below)

**Describe the bug**
The rules for the transport order profile as defined at [this page](https://otm5developerportal.redoc.ly/developer-portal/profiles/transport_orders_profile/) are not evaluated by the validation endpoint for transport orders.

**To Reproduce**
1. Open a REST client
2. Perform a PUT operation on `https://otm5-documentation-api.services.simacan.com/api/v5/validate/transportOrders` with header `Content-Type: application/json` and the body below.
3. Notice that the validation tool return 200 OK.
4. Notice that the body doesn't comply to e.g. the rule: `A consignment must have at least one goods item to be transported.`

Body
```json
{
  "consignments": [
    {
      "associationType": "inline",
      "entity": {
        "goods": [
        ]
      }
    }
  ]
}
```

**Expected behavior**
Validation tool to check and report all the rules as mentioned in the transport order profile:
* A transport order must at least have one consignment.
* A consignment must have at least one goods item to be transported.
* A consignment must at least have one load action and one unload action. It can have multiple if multiple trips are involved.
* Every load and unload actions must have a location.
* All other fields are optional. For example, each consignment can have a constraint determining between what time windows the goods need to be delivered.

**Screenshots**
![image](https://github.com/opentripmodel/otm5-change-requests/assets/7961582/565b6a9d-3aaf-4874-a20c-dfc0ad032c8d)

**Comment by bmeesters** [comment]
Thanks, I'll double check why not the same rules have applied.

**Comment by ESchouten** [comment]
Any news on this?

**Comment by bmeesters** [comment]
@ESchouten Sorry no news. It does not get any priority at the moment. So I cannot give you a date.

**Comment by bmeesters** [comment]
Since TNO is working on a tool that can do this and more we expect that the validation tool can be deprecated and turned off. So we will not fix it (even though we agree that this is a bug).

**Comment by Michiel-s** [comment]
The JSON validator module is ready and integrated in Semantic Treehouse. The running instance at https://sutc.semantic-treehouse.nl is at the disposal of the OTM team.

OTM profiles need to be registered in order to configure the validator. That is work to be done.

It is possible to either upload a json schema as validation artefact for the profile or let Semantic Treehouse generate the json schema.
